# Generated by Django 4.2 on 2025-05-19 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socio_lotacao', models.CharField(blank=True, max_length=255, null=True)),
                ('secretaria', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=10, null=True, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('data_nasc', models.DateField(blank=True, null=True)),
                ('cpf', models.CharField(max_length=14, null=True, unique=True)),
                ('rg', models.CharField(blank=True, max_length=20, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('data_socio', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo'), ('Suspenso', 'Suspenso')], default='Ativo', max_length=20)),
                ('documento_vencimento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocioTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_admissao', models.DateField(blank=True, null=True)),
                ('cargo', models.CharField(blank=True, max_length=255, null=True)),
                ('lotacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabalhos', to='cadastro.lotacao')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabalhos', to='cadastro.socio')),
            ],
        ),
        migrations.CreateModel(
            name='SocioEndereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('bairro', models.CharField(blank=True, max_length=255, null=True)),
                ('cidade', models.CharField(blank=True, max_length=255, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='cadastro.socio')),
            ],
        ),
        migrations.CreateModel(
            name='SocioDependent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependentes', to='cadastro.socio')),
            ],
        ),
        migrations.AddField(
            model_name='lotacao',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotacoes', to='cadastro.socio'),
        ),
    ]
