# Generated by Django 5.1.5 on 2025-03-12 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocioTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, max_length=255, null=True)),
                ('lotacao', models.CharField(blank=True, max_length=255, null=True)),
                ('secretaria', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='socio',
            name='data_nasc',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='data_socio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='rg',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='SocioDependent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependentes', to='cadastro.socio')),
            ],
        ),
        migrations.CreateModel(
            name='SocioEndereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('bairro', models.CharField(blank=True, max_length=255, null=True)),
                ('cidade', models.CharField(blank=True, max_length=255, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='cadastro.socio')),
            ],
        ),
        migrations.AddField(
            model_name='socio',
            name='trabalho',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.sociotrabalho'),
        ),
    ]
