# Generated by Django 5.1.5 on 2025-03-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_sociotrabalho_socio_data_nasc_socio_data_socio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socioendereco',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
