# Generated by Django 5.1.5 on 2025-03-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_socioendereco_cep'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociotrabalho',
            name='data_admissao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
