# Generated by Django 5.1.5 on 2025-04-08 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_sociotrabalho_data_admissao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='socio',
            name='trabalho',
        ),
        migrations.AddField(
            model_name='sociotrabalho',
            name='socio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cargo', to='cadastro.socio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sociotrabalho',
            name='lotacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotacao', to='cadastro.lotacao'),
        ),
    ]
