# Generated by Django 5.1.5 on 2025-04-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_lotacao_remove_socio_trabalho_sociotrabalho_socio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lotacao',
            old_name='nome',
            new_name='socio_lotacao',
        ),
        migrations.RemoveField(
            model_name='sociotrabalho',
            name='secretaria',
        ),
        migrations.AddField(
            model_name='lotacao',
            name='secretaria',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
