# Generated by Django 5.1.5 on 2025-04-08 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_rename_nome_lotacao_socio_lotacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociotrabalho',
            name='lotacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotacoes', to='cadastro.lotacao'),
        ),
        migrations.AlterField(
            model_name='sociotrabalho',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='cadastro.socio'),
        ),
    ]
