# Generated by Django 5.1.5 on 2025-04-15 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_alter_sociotrabalho_lotacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotacao',
            name='socio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lotacoes', to='cadastro.socio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sociotrabalho',
            name='lotacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabalhos', to='cadastro.lotacao'),
        ),
        migrations.AlterField(
            model_name='sociotrabalho',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabalhos', to='cadastro.socio'),
        ),
    ]
